- name: Setup PostgreSQL Master
  hosts: db_master
  become: yes
  vars:
    db_name: "db_customers"
    db_user: "admpetr"
    db_pass: "eve@123"
    repl_user: "replicator"
    repl_pass: "repl_password"
  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql-16
          - python3-psycopg2
          - acl
        state: present
        update_cache: yes

    - name: Allow remote connections (postgresql.conf)
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"

    - name: Configure WAL level for replication
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        line: "{{ item }}"
      loop:
        - "wal_level = replica"
        - "max_wal_senders = 10"
        - "hot_standby = on"

    - name: Configure pg_hba.conf for replication
      blockinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        block: |
          host    replication     {{ repl_user }}   0.0.0.0/0      scram-sha-256
          host    all             all               0.0.0.0/0      scram-sha-256

    - name: Restart PostgreSQL to apply changes
      service:
        name: postgresql
        state: restarted

    - name: Create Database
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"

    - name: Create DB User
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        db: "{{ db_name }}"
        priv: "ALL"

    - name: Create Replication User
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ repl_user }}"
        password: "{{ repl_pass }}"
        role_attr_flags: REPLICATION


- name: Setup PostgreSQL Replica
  hosts: db_replica
  become: yes
  vars:
    master_ip: "{{ hostvars[groups['db_master'][0]]['ansible_host'] }}"
    repl_user: "replicator"
    repl_pass: "repl_password"
  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql-16
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Stop PostgreSQL before replication setup
      service:
        name: postgresql
        state: stopped

    - name: Clear PostgreSQL data directory
      file:
        path: /var/lib/postgresql/16/main
        state: absent

    - name: Create empty data directory
      file:
        path: /var/lib/postgresql/16/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Backup from Master (Base Backup)
      become_user: postgres
      shell: |
        PGPASSWORD='{{ repl_pass }}' pg_basebackup -h {{ master_ip }} -D /var/lib/postgresql/16/main -U {{ repl_user }} -P -v -R -X stream
      ignore_errors: yes

    - name: Fix permissions
      file:
        path: /var/lib/postgresql/16/main
        owner: postgres
        group: postgres
        recurse: yes

    - name: Start PostgreSQL Replica
      service:
        name: postgresql
        state: started

- name: Setup Telegram Bot
  hosts: bot
  become: yes
  vars:
    db_host: "{{ hostvars[groups['db_master'][0]]['ansible_host'] }}"
    db_name: "db_customers"
    db_user: "admpetr"
    db_pass: "eve@123"
    bot_token: "8504876037:AAFm_4EOwq5y7IqbIiI3NCuuJS4W_HTVuMk"
    project_dir: "/opt/tg_bot"

  tasks:
    - name: Install System dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Clean project directory (fix git error)
      file:
        path: "{{ project_dir }}"
        state: absent

    - name: Clone Bot Code from GitHub
      git:
        repo: 'https://github.com/vac221234-source/DockerAnsible.git'
        dest: "{{ project_dir }}"
        version: docker
        force: yes

    - name: Install Python requirements
      pip:
        requirements: "{{ project_dir }}/bot/requirements.txt"
        virtualenv: "{{ project_dir }}/venv"
        virtualenv_command: python3 -m venv

    - name: Create .env file
      copy:
        dest: "{{ project_dir }}/bot/.env"
        content: |
          BOT_TOKEN={{ bot_token }}
          DB_HOST={{ db_host }}
          DB_PORT=5432
          DB_NAME={{ db_name }}
          DB_USER={{ db_user }}
          DB_PASS={{ db_pass }}

    - name: Create Systemd Service
      copy:
        dest: /etc/systemd/system/tgbot.service
        mode: '0644'
        content: |
          [Unit]
          Description=Telegram Bot Service
          After=network.target

          [Service]
          User=root
          WorkingDirectory={{ project_dir }}/bot
          ExecStart={{ project_dir }}/venv/bin/python3 {{ project_dir }}/bot/main.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable Bot Service (stopped)
      systemd:
        name: tgbot
        enabled: yes
        state: stopped
        daemon_reload: yes
